let shopItemsData = [
  {
    id: "joy",
    name: "nike sneaker",
    price: 179999 / 100,
    desc: "more details on produvt",
    img: "./img/p1.jpg",
  },
  {
    id: "jooy",
    name: "puma sneaker",
    price: 69999 / 100,
    desc: "puma details on produvt",
    img: "./img/p2.jpg",
  },
  {
    id: "joyy",
    name: "puma sneaker",
    price: 99999 / 100,
    desc: "more details on produvt",
    img: "./img/p3.jpg",
  },
  {
    id: "jjoy",
    name: "converse sneaker",
    price: 99999 / 100,
    desc: "more details on produvt",
    img: "./img/p4.jpg",
  },
  {
    id: "jjooy",
    name: "sneaker",
    price: 249999 / 100,
    desc: "more details on produvt",
    img: "./img/p6.jpg",
  },
  {
    id: "jjoyy",
    name: "sneaker",
    price: 129999 / 100,
    desc: "more details on produvt",
    img: "./img/p7.jpg",
  },
  {
    id: "jjjooy",
    name: "sneaker",
    price: 34999 / 100,
    desc: "more details on produvt",
    img: "./img/p8.jpeg",
  },

  {
    id: "jjoooy",
    name: "sneaker",
    price: 16999 / 100,
    desc: "more details on produvt",
    img: "./img/p9.jpg",
  },
  {
    id: "jjoyyy",
    name: "converse sneaker",
    price: 24999 / 100,
    desc: "more details on produvt",
    img: "./img/p10.png",
  },
  {
    id: "jjoyyy",
    name: "converse sneaker",
    price: 24999 / 100,
    desc: "more details on produvt",
    img: "./img/p-1.jpg",
  },
  {
    id: "jjoyyy",
    name: "converse sneaker",
    price: 24999 / 100,
    desc: "more details on produvt",
    img: "./img/p-2.jpg",
  },
  {
    id: "jjoyyy",
    name: "converse sneaker",
    price: 24999 / 100,
    desc: "more details on produvt",
    img: "./img/p-3.jpg",
  },
];
